[package]
name = "rocky"
version = "0.1.0"
authors = ["Laurent Belmonte <laurent.belmonte@gmail.com>"]

[dependencies]
byteorder="1"
rand="0.4.2"
unicode-segmentation = "0.1.2"
roaring="0.5.2"
rocksdb= "0.10.0"
